use std::sync::Arc;

use axum::{middleware, Router};
use tokio::sync::broadcast;
use tower_http::{compression::CompressionLayer, trace::TraceLayer};
use utoipa::OpenApi;
use utoipa_swagger_ui::SwaggerUi;

use crate::{
    app_server::DynAppServer,
    app_server_api::{
        AccountLoginCompleted, AccountResponse, ActivePermissionProfile, AppSummary,
        ComposerPermissionsPreset, ComposerSettingsResponse, ComposerSettingsUpdateRequest,
        ComposerSettingsUpdateResponse, ConfiguredMcpSecret, ConfiguredMcpServer,
        ConfiguredMcpServerListResponse, ConfiguredMcpTransport, LoginStartResponse,
        MarketplaceAddResponse, McpAuthStatus, McpConfigMutationResponse, McpOAuthLoginRequest,
        McpOAuthLoginResponse, McpReloadResponse, McpResource, McpResourceReadResponse,
        McpResourceTemplate, McpServerInstallRequest, McpServerListResponse,
        McpServerRemoveRequest, McpServerStatus, McpServerStatusDetail, McpServerToggleRequest,
        McpServerTransportRequest, McpServerUpdateRequest, McpTool, ModelListResponse,
        NativeConfigLayerMetadata, NativeConfigLeafEdit, NativeConfigOverriddenMetadata,
        NativeConfigWriteResult, NativeConfigWriteStatus, NativeConfigWriteTarget,
        PendingTimelineRequestSummary, PermissionProfileListResponse, PermissionProfileSummary,
        PluginDetail, PluginInstallResponse, PluginInterface, PluginListResponse,
        PluginMarketplaceEntry, PluginReadResponse, PluginSummary, RateLimitsResponse,
        RawAppServerResponse, SkillErrorInfo, SkillInterface, SkillMetadata, SkillsCatalogResponse,
        ThreadCommandResponse, ThreadItemSnapshot, ThreadListResponse, ThreadLiveState,
        ThreadSection, ThreadSectionAppearance, ThreadSettingsUpdateRequest,
        ThreadSubagentListResponse, ThreadSubagentSummary, ThreadTimelineFileChangeEntry,
        ThreadTimelineRow, ThreadTimelineSnapshot, ThreadTimelineSnapshotItem,
        ThreadTimelineWindowPage, ThreadTimelineWorkDetailRow, ThreadTimelineWorkSummary,
        ThreadTurnSnapshot, ThreadViewResponse, ThreadViewThreadSummary, TimelineFileAttachment,
        TimelineItemDeltaPayload, TimelineItemUpsertPayload, TimelineSkillMention,
        TimelineThreadMetadataPayload, TimelineThreadStatusPayload, TimelineTurnUpsertPayload,
        TimelineUpdateSource, UserInput,
    },
    config::Config,
    error::{ApiErrorBody, NativeConfigWriteErrorCode, NativeConfigWriteErrorData},
    events::{ProjectChanged, ThreadProjectUpdated},
    queue::{
        QueuedInputCreateRequest, QueuedInputDeleteResponse, QueuedInputListResponse,
        QueuedInputResponse,
    },
    routes,
    routes::{
        account::AccountQuery,
        app_surfaces::{
            AppSurfaceBridgeError, AppSurfaceBridgeRequest, AppSurfaceBridgeResponse,
            AppSurfaceDocumentQuery, AppSurfacePresentationAction,
            AppSurfacePresentationRequestDto, AppSurfacePresentationResponse, AppSurfaceSessionDto,
            AppSurfaceSessionReadResponse, AppSurfaceSessionResponse,
        },
        approvals::{ApprovalDecisionRequest, ApprovalListResponse},
        automations::{
            AutomationCreateRequest, AutomationDeleteResponse, AutomationDto, AutomationListQuery,
            AutomationListResponse, AutomationRepeatEvery, AutomationRepeatUnit,
            AutomationResponse, AutomationSchedule, AutomationUpdateRequest,
        },
        capabilities::{
            AppServerCapabilities, CapabilitiesResponse, GatewayCapabilities, TerminalCapabilities,
        },
        composer_settings::ComposerSettingsQuery,
        events::EventListResponse,
        file_preview::FilePreviewQuery,
        health::{HealthResponse, ReadyResponse},
        kodex_control_plugin::{
            KodexControlPluginInstallResponse, KodexControlPluginStatusKind,
            KodexControlPluginStatusResponse,
        },
        mcp::{McpResourceReadQuery, McpServersQuery},
        models::ModelsQuery,
        notifications::{
            CurrentPushSubscriptionQuery, CurrentPushSubscriptionResponse,
            NotificationStatusResponse, PushSubscriptionDeleteResponse, PushSubscriptionResponse,
            PushSubscriptionUpsertRequest, PushSubscriptionUpsertResponse,
            TestNotificationResponse,
        },
        permission_profiles::PermissionProfilesQuery,
        projects::{
            CreateProjectRequest, MoveProjectRequest, Project, ProjectListResponse, ProjectRoot,
            UpdateProjectRequest,
        },
        self_control::{
            SelfControlAppSurfacePresentationRequest, SelfControlApprovalDecisionRequest,
            SelfControlApprovalDecisionResponse, SelfControlApprovalPolicyResult,
            SelfControlAutomationCreateRequest, SelfControlAutomationResponse,
            SelfControlAutomationRunNowRequest, SelfControlAutomationRunNowResponse,
            SelfControlAutomationUpdateRequest, SelfControlAutomationValidateRequest,
            SelfControlAutomationValidateResponse, SelfControlCapabilities,
            SelfControlCreateThreadRequest, SelfControlGeneratedAppSurfaceUpsertRequest,
            SelfControlMarkThreadSeenRequest, SelfControlMutationRequest,
            SelfControlRenameThreadRequest, SelfControlRequestedBy, SelfControlSource,
            SelfControlSourceType, SelfControlStatusResponse, SelfControlThreadInputAction,
            SelfControlThreadInputRequest, SelfControlThreadInputResponse,
            SelfControlThreadPayloadMutationRequest, SelfControlThreadSettingsUpdateRequest,
            SelfControlThreadSpawnRequest, SelfControlThreadSpawnResponse,
        },
        self_control_sections::{
            SelfControlCreateThreadSectionRequest, SelfControlMoveThreadToSectionRequest,
            SelfControlUpdateThreadSectionRequest,
        },
        skills::{SkillIconQuery, SkillsQuery},
        subagents::ThreadSubagentListQuery,
        terminals::TerminalDeleteResponse,
        thread_presence::{ThreadViewPresenceRequest, ThreadViewPresenceSnapshotRequest},
        thread_sections::{
            CreateThreadSectionRequest, MoveThreadToSectionRequest, ThreadSectionListQuery,
            ThreadSectionListResponse, ThreadSectionResponse, UpdateThreadSectionRequest,
        },
        thread_settings::{
            ThreadSettingsResponse, ThreadSettingsUpdateResponse, ThreadSettingsUpdated,
        },
        threads::{
            ChatThreadListQuery, CreateChatThreadRequest, CreateThreadRequest,
            MarkThreadSeenRequest, RenameThreadRequest, RenameThreadResponse,
            SidebarThreadListResponse, SidebarThreadSummary, SidebarThreadsResponse,
            ThreadAttachDisposition, ThreadAttachResponse, ThreadListQuery,
            ThreadNotificationSettingsResponse, ThreadNotificationSettingsUpdate,
            ThreadNotificationSettingsUpdateRequest, ThreadProjectUpdateRequest,
            ThreadReadStateUpdate, ThreadTimelinePageQuery,
        },
        turns::{
            ThreadCompactDisposition, ThreadCompactResponse, ThreadInputResponse,
            ThreadInterruptCurrentDisposition, ThreadInterruptCurrentResponse, TurnStartRequest,
            TurnSteerRequest,
        },
        uploads::{
            FileUploadRequest, FileUploadResponse, ImageUpload, ImageUploadRequest,
            ImageUploadResponse,
        },
    },
    static_assets,
    store::{
        AppSurfaceCsp, AppSurfaceGrants, AppSurfacePermissions, AppSurfaceProvider,
        AppSurfaceResourceGrant, AppSurfaceSession, AppSurfaceSessionStatus, AppSurfaceToolGrant,
        Approval, ApprovalSource, AutomationStatus, EventEnvelope, QueuedInput,
        QueuedInputPriority, QueuedInputStatus, Store, ThreadRead,
    },
    subagents::ThreadSubagentsChanged,
    terminal::{
        CreateTerminalSession, TerminalSessionInfo, TerminalSessionListResponse,
        TerminalSessionResponse, TerminalSessionStatus,
    },
    thread_view::{ThreadViewPatch, ThreadViewStore},
};

#[derive(Clone)]
pub struct AppState {
    pub config: Arc<Config>,
    pub store: Store,
    pub app_server: DynAppServer,
    pub approvals: crate::approvals::ApprovalService,
    pub events: broadcast::Sender<EventEnvelope>,
    pub skills: crate::skills::SkillCatalogCache,
    pub notifications: crate::notifications::NotificationService,
    pub thread_presence: crate::thread_presence::ThreadPresence,
    pub thread_views: ThreadViewStore,
    pub thread_input_locks: crate::turn_lifecycle::ThreadInputLocks,
    pub terminals: crate::terminal::TerminalManager,
}

impl AppState {
    pub fn new(config: Config, store: Store, app_server: DynAppServer) -> Self {
        let (events, _) = broadcast::channel(1024);
        let notifications =
            crate::notifications::NotificationService::from_config(&config.notifications);
        let config = Arc::new(config);
        let terminals = crate::terminal::TerminalManager::new(
            config.projects.home_dir.clone(),
            config.codex.home.clone(),
        );
        Self {
            config,
            store,
            app_server,
            approvals: crate::approvals::ApprovalService::default(),
            events,
            skills: crate::skills::SkillCatalogCache::default(),
            notifications,
            thread_presence: crate::thread_presence::ThreadPresence::default(),
            thread_views: ThreadViewStore::default(),
            thread_input_locks: crate::turn_lifecycle::ThreadInputLocks::default(),
            terminals,
        }
    }

    pub fn with_notification_sender(
        mut self,
        sender: Arc<dyn crate::notifications::PushSender>,
    ) -> Self {
        self.notifications = crate::notifications::NotificationService::new(sender);
        self
    }
}

#[derive(OpenApi)]
#[openapi(
    paths(
        crate::routes::health::healthz,
        crate::routes::health::readyz,
        crate::routes::capabilities::capabilities,
        crate::routes::terminals::list_terminals,
        crate::routes::terminals::create_terminal,
        crate::routes::terminals::delete_terminal,
        crate::routes::composer_settings::read_composer_settings,
        crate::routes::composer_settings::update_composer_settings,
        crate::routes::permission_profiles::list_permission_profiles,
        crate::events::events,
        crate::events::debug_events,
        crate::routes::projects::list_projects,
        crate::routes::projects::create_project,
        crate::routes::projects::get_project,
        crate::routes::projects::update_project,
        crate::routes::projects::move_project,
        crate::routes::projects::delete_project,
        crate::routes::thread_sections::list_thread_sections,
        crate::routes::thread_sections::create_thread_section,
        crate::routes::thread_sections::update_thread_section,
        crate::routes::thread_sections::delete_thread_section,
        crate::routes::thread_sections::list_section_threads,
        crate::routes::thread_sections::move_thread_to_section,
        crate::routes::self_control_sections::create_section,
        crate::routes::self_control_sections::update_section,
        crate::routes::self_control_sections::delete_section,
        crate::routes::self_control_sections::move_thread,
        crate::routes::threads::list_threads,
        crate::routes::threads::get_sidebar_threads,
        crate::routes::threads::create_thread,
        crate::routes::threads::list_chat_threads,
        crate::routes::threads::create_chat_thread,
        crate::routes::subagents::list_subagents,
        crate::routes::threads::get_thread,
        crate::routes::threads::get_thread_timeline_page,
        crate::routes::threads::attach_thread,
        crate::routes::threads::rename_thread,
        crate::routes::threads::update_thread_project,
        crate::routes::thread_settings::get_thread_settings,
        crate::routes::thread_settings::update_thread_settings,
        crate::routes::threads::update_thread_notifications,
        crate::routes::threads::resume_thread,
        crate::routes::threads::fork_thread,
        crate::routes::threads::archive_thread,
        crate::routes::threads::mark_thread_seen,
        crate::routes::turns::start_turn,
        crate::routes::turns::submit_thread_input,
        crate::routes::turns::steer_turn,
        crate::routes::turns::compact_thread,
        crate::routes::turns::interrupt_current_turn,
        crate::routes::turns::interrupt_turn,
        crate::routes::app_surfaces::get_thread_app_surface,
        crate::routes::app_surfaces::app_surface_document,
        crate::routes::app_surfaces::app_surface_bridge,
        crate::queue::list_queued_inputs,
        crate::queue::create_queued_input,
        crate::queue::retry_queued_input,
        crate::queue::steer_queued_input,
        crate::queue::delete_queued_input,
        crate::routes::file_preview::preview_thread_file,
        crate::routes::uploads::upload_images,
        crate::routes::uploads::upload_thread_files,
        crate::routes::approvals::list_approvals,
        crate::routes::approvals::get_approval,
        crate::routes::approvals::decide_approval,
        crate::routes::automations::list_automations,
        crate::routes::automations::create_automation,
        crate::routes::automations::get_automation,
        crate::routes::automations::update_automation,
        crate::routes::automations::pause_automation,
        crate::routes::automations::resume_automation,
        crate::routes::automations::delete_automation,
        crate::routes::account::read_account,
        crate::routes::account::start_login,
        crate::routes::account::cancel_login,
        crate::routes::account::logout,
        crate::routes::account::read_rate_limits,
        crate::routes::models::list_models,
        crate::routes::notifications::notification_status,
        crate::routes::notifications::upsert_push_subscription,
        crate::routes::notifications::delete_push_subscription,
        crate::routes::notifications::current_push_subscription,
        crate::routes::notifications::delete_current_push_subscription,
        crate::routes::notifications::test_notification,
        crate::routes::thread_presence::update_thread_view_presence,
        crate::routes::thread_presence::replace_thread_view_presence,
        crate::routes::skills::list_skills,
        crate::routes::skills::preview_skill_icon,
        crate::routes::kodex_control_plugin::kodex_control_plugin_status,
        crate::routes::kodex_control_plugin::install_kodex_control_plugin,
        crate::routes::mcp::list_configured_mcp_servers,
        crate::routes::mcp::list_mcp_servers,
        crate::routes::mcp::add_mcp_server,
        crate::routes::mcp::update_mcp_server,
        crate::routes::mcp::set_mcp_server_enabled,
        crate::routes::mcp::remove_mcp_server,
        crate::routes::mcp::read_mcp_resource,
        crate::routes::mcp::start_mcp_oauth_login,
        crate::routes::mcp::reload_mcp_servers,
        crate::routes::self_control::self_control_status,
        crate::routes::self_control::list_self_control_projects,
        crate::routes::self_control::get_self_control_project,
        crate::routes::self_control::list_self_control_threads,
        crate::routes::self_control::get_self_control_sidebar_threads,
        crate::routes::self_control::get_self_control_thread,
        crate::routes::self_control::get_self_control_thread_timeline_page,
        crate::routes::self_control::list_self_control_subagents,
        crate::routes::self_control::list_self_control_queued_inputs,
        crate::routes::self_control::get_self_control_app_surface,
        crate::routes::self_control::upsert_self_control_generated_app_surface,
        crate::routes::self_control::request_self_control_app_surface_presentation,
        crate::routes::self_control::archive_self_control_app_surface,
        crate::routes::self_control::create_self_control_thread,
        crate::routes::self_control::attach_self_control_thread,
        crate::routes::self_control::resume_self_control_thread,
        crate::routes::self_control::fork_self_control_thread,
        crate::routes::self_control::rename_self_control_thread,
        crate::routes::self_control::update_self_control_thread_settings,
        crate::routes::self_control::archive_self_control_thread,
        crate::routes::self_control::mark_self_control_thread_seen,
        crate::routes::self_control::compact_self_control_thread,
        crate::routes::self_control::interrupt_current_self_control_thread,
        crate::routes::self_control::send_self_control_thread_input,
        crate::routes::self_control::spawn_self_control_thread,
        crate::routes::self_control::list_self_control_automations,
        crate::routes::self_control::create_self_control_automation,
        crate::routes::self_control::get_self_control_automation,
        crate::routes::self_control::update_self_control_automation,
        crate::routes::self_control::delete_self_control_automation,
        crate::routes::self_control::pause_self_control_automation,
        crate::routes::self_control::resume_self_control_automation,
        crate::routes::self_control::run_self_control_automation_now,
        crate::routes::self_control::validate_self_control_automation,
        crate::routes::self_control::list_self_control_approvals,
        crate::routes::self_control::get_self_control_approval,
        crate::routes::self_control::decide_self_control_approval,
        crate::routes::self_control::list_self_control_events
    ),
    components(schemas(
        ApiErrorBody,
        NativeConfigWriteErrorCode,
        NativeConfigWriteErrorData,
        HealthResponse,
        ReadyResponse,
        CapabilitiesResponse,
        GatewayCapabilities,
        TerminalCapabilities,
        AppServerCapabilities,
        CreateTerminalSession,
        TerminalDeleteResponse,
        TerminalSessionInfo,
        TerminalSessionListResponse,
        TerminalSessionResponse,
        TerminalSessionStatus,
        ComposerSettingsQuery,
        ComposerSettingsResponse,
        ComposerSettingsUpdateRequest,
        ComposerSettingsUpdateResponse,
        ComposerPermissionsPreset,
        ActivePermissionProfile,
        PermissionProfilesQuery,
        PermissionProfileListResponse,
        PermissionProfileSummary,
        EventEnvelope,
        EventListResponse,
        ProjectChanged,
        ThreadProjectUpdated,
        Project,
        ProjectListResponse,
        CreateProjectRequest,
        UpdateProjectRequest,
        MoveProjectRequest,
        ProjectRoot,
        ThreadProjectUpdateRequest,
        RawAppServerResponse,
        ThreadListResponse,
        ThreadViewResponse,
        ThreadViewThreadSummary,
        ThreadTimelineSnapshot,
        ThreadTimelineRow,
        ThreadTimelineWorkDetailRow,
        ThreadTimelineWorkSummary,
        ThreadTimelineFileChangeEntry,
        ThreadTimelineSnapshotItem,
        PendingTimelineRequestSummary,
        ThreadViewPatch,
        ThreadTurnSnapshot,
        ThreadItemSnapshot,
        ThreadLiveState,
        ThreadCommandResponse,
        TimelineUpdateSource,
        TimelineTurnUpsertPayload,
        TimelineItemUpsertPayload,
        TimelineItemDeltaPayload,
        TimelineSkillMention,
        TimelineThreadStatusPayload,
        TimelineThreadMetadataPayload,
        ThreadListQuery,
        ChatThreadListQuery,
        ThreadTimelinePageQuery,
        SidebarThreadsResponse,
        ThreadSection,
        ThreadSectionAppearance,
        CreateThreadSectionRequest,
        UpdateThreadSectionRequest,
        MoveThreadToSectionRequest,
        ThreadSectionListQuery,
        ThreadSectionListResponse,
        ThreadSectionResponse,
        SelfControlCreateThreadSectionRequest,
        SelfControlUpdateThreadSectionRequest,
        SelfControlMoveThreadToSectionRequest,
        SidebarThreadListResponse,
        SidebarThreadSummary,
        ThreadTimelineWindowPage,
        ThreadAttachResponse,
        ThreadAttachDisposition,
        CreateThreadRequest,
        CreateChatThreadRequest,
        RenameThreadRequest,
        RenameThreadResponse,
        ThreadSettingsUpdateRequest,
        ThreadSettingsUpdateResponse,
        ThreadSettingsResponse,
        ThreadSettingsUpdated,
        ThreadNotificationSettingsResponse,
        ThreadNotificationSettingsUpdate,
        ThreadNotificationSettingsUpdateRequest,
        MarkThreadSeenRequest,
        ThreadReadStateUpdate,
        ThreadSubagentSummary,
        ThreadSubagentListResponse,
        ThreadSubagentListQuery,
        ThreadSubagentsChanged,
        ThreadRead,
        AppSurfaceProvider,
        AppSurfaceSessionStatus,
        AppSurfaceCsp,
        AppSurfacePermissions,
        AppSurfaceGrants,
        AppSurfaceToolGrant,
        AppSurfaceResourceGrant,
        AppSurfacePresentationAction,
        AppSurfacePresentationRequestDto,
        AppSurfacePresentationResponse,
        AppSurfaceSession,
        AppSurfaceSessionDto,
        AppSurfaceSessionReadResponse,
        AppSurfaceSessionResponse,
        AppSurfaceDocumentQuery,
        AppSurfaceBridgeRequest,
        AppSurfaceBridgeResponse,
        AppSurfaceBridgeError,
        UserInput,
        TimelineFileAttachment,
        TurnStartRequest,
        TurnSteerRequest,
        ThreadCompactResponse,
        ThreadCompactDisposition,
        ThreadInputResponse,
        ThreadInterruptCurrentResponse,
        ThreadInterruptCurrentDisposition,
        QueuedInput,
        QueuedInputStatus,
        QueuedInputPriority,
        QueuedInputCreateRequest,
        QueuedInputListResponse,
        QueuedInputResponse,
        QueuedInputDeleteResponse,
        FilePreviewQuery,
        FileUploadRequest,
        FileUploadResponse,
        ImageUpload,
        ImageUploadRequest,
        ImageUploadResponse,
        Approval,
        ApprovalSource,
        ApprovalListResponse,
        ApprovalDecisionRequest,
        AutomationListQuery,
        AutomationSchedule,
        AutomationRepeatEvery,
        AutomationRepeatUnit,
        AutomationStatus,
        AutomationCreateRequest,
        AutomationUpdateRequest,
        AutomationDto,
        AutomationResponse,
        AutomationListResponse,
        AutomationDeleteResponse,
        AccountQuery,
        AccountResponse,
        AccountLoginCompleted,
        LoginStartResponse,
        RateLimitsResponse,
        ModelsQuery,
        ModelListResponse,
        NotificationStatusResponse,
        PushSubscriptionResponse,
        PushSubscriptionUpsertRequest,
        PushSubscriptionUpsertResponse,
        PushSubscriptionDeleteResponse,
        CurrentPushSubscriptionQuery,
        CurrentPushSubscriptionResponse,
        TestNotificationResponse,
        ThreadViewPresenceRequest,
        ThreadViewPresenceSnapshotRequest,
        SkillsQuery,
        SkillIconQuery,
        SkillsCatalogResponse,
        SkillMetadata,
        SkillInterface,
        SkillErrorInfo,
        AppSummary,
        MarketplaceAddResponse,
        PluginDetail,
        PluginInstallResponse,
        PluginInterface,
        PluginListResponse,
        PluginMarketplaceEntry,
        PluginReadResponse,
        PluginSummary,
        KodexControlPluginStatusKind,
        KodexControlPluginStatusResponse,
        KodexControlPluginInstallResponse,
        McpServersQuery,
        McpResourceReadQuery,
        McpServerStatusDetail,
        McpServerListResponse,
        McpServerStatus,
        McpAuthStatus,
        McpTool,
        McpResource,
        McpResourceTemplate,
        McpResourceReadResponse,
        McpOAuthLoginRequest,
        McpOAuthLoginResponse,
        McpReloadResponse,
        ConfiguredMcpServerListResponse,
        ConfiguredMcpServer,
        ConfiguredMcpTransport,
        ConfiguredMcpSecret,
        McpServerInstallRequest,
        McpServerTransportRequest,
        McpServerToggleRequest,
        McpServerUpdateRequest,
        McpServerRemoveRequest,
        NativeConfigWriteTarget,
        NativeConfigLeafEdit,
        NativeConfigWriteResult,
        NativeConfigWriteStatus,
        NativeConfigOverriddenMetadata,
        NativeConfigLayerMetadata,
        McpConfigMutationResponse,
        SelfControlStatusResponse,
        SelfControlCapabilities,
        SelfControlSource,
        SelfControlSourceType,
        SelfControlRequestedBy,
        SelfControlGeneratedAppSurfaceUpsertRequest,
        SelfControlAppSurfacePresentationRequest,
        SelfControlCreateThreadRequest,
        SelfControlThreadInputRequest,
        SelfControlThreadInputResponse,
        SelfControlThreadInputAction,
        SelfControlMutationRequest,
        SelfControlThreadPayloadMutationRequest,
        SelfControlRenameThreadRequest,
        SelfControlThreadSettingsUpdateRequest,
        SelfControlMarkThreadSeenRequest,
        SelfControlThreadSpawnRequest,
        SelfControlThreadSpawnResponse,
        SelfControlAutomationCreateRequest,
        SelfControlAutomationUpdateRequest,
        SelfControlAutomationResponse,
        SelfControlAutomationRunNowRequest,
        SelfControlAutomationRunNowResponse,
        SelfControlAutomationValidateRequest,
        SelfControlAutomationValidateResponse,
        SelfControlApprovalDecisionRequest,
        SelfControlApprovalDecisionResponse,
        SelfControlApprovalPolicyResult
    ))
)]
pub struct ApiDoc;

pub fn build_router(state: AppState) -> Router {
    let mut router = Router::new()
        .merge(routes::health::router())
        .merge(routes::capabilities::router())
        .merge(routes::terminals::router())
        .merge(routes::composer_settings::router())
        .merge(routes::events::router())
        .merge(routes::projects::router())
        .merge(routes::threads::router())
        .merge(routes::subagents::router())
        .merge(routes::thread_sections::router())
        .merge(routes::self_control_sections::router())
        .merge(routes::thread_settings::router())
        .merge(routes::turns::router())
        .merge(routes::app_surfaces::router())
        .merge(crate::queue::router())
        .merge(routes::file_preview::router())
        .merge(routes::uploads::router())
        .merge(routes::approvals::router())
        .merge(routes::automations::router())
        .merge(routes::account::router())
        .merge(routes::models::router())
        .merge(routes::notifications::router())
        .merge(routes::thread_presence::router())
        .merge(routes::permission_profiles::router())
        .merge(routes::skills::router())
        .merge(routes::kodex_control_plugin::router())
        .merge(routes::mcp::router())
        .merge(routes::self_control::router())
        .merge(SwaggerUi::new("/docs").url("/openapi.json", ApiDoc::openapi()))
        .with_state(state.clone());

    if let Some(dist_dir) = state.config.frontend.dist_dir.clone() {
        router = static_assets::attach_frontend(router, dist_dir);
    }

    router
        .layer(middleware::from_fn(
            crate::performance::route_timing_middleware,
        ))
        .layer(CompressionLayer::new())
        .layer(TraceLayer::new_for_http())
}
