import { MantineProvider } from '@mantine/core';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { act, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { createContext, useContext, type ComponentProps, type ReactNode } from 'react';
import { expect, it, vi } from 'vitest';
import { NativeShell } from './NativeShell';
import { DEFAULT_APPEARANCE_PREFERENCES } from '../theme/appearancePreferences';
import { useNativeCatalogSnapshot } from './NativeCatalogContext';
import type { CatalogSnapshot } from './client';
import type { WorkspaceProvider } from '../workspace/WorkspaceProvider';
import { renameThread } from '../api/client';
const rpc = vi.hoisted(() => ({ watchCatalog: vi.fn(), renameChat: vi.fn() }));
const actionsContext = createContext<NonNullable<ComponentProps<typeof WorkspaceProvider>['threadActions']>>({});
vi.mock('./client', () => ({ mastraClient: rpc }));
vi.mock('./NativeHostBoundary', () => ({ useNativeHost: () => ({ instanceId: 'instance' }) }));
vi.mock('./useNativeAccount', () => ({ useNativeAccount: () => ({ error: null, logout: vi.fn() }) }));
vi.mock('./NativeAccountMenu', () => ({ NativeAccountMenu: () => null }));
vi.mock('./NativeThreadPane', () => ({ NativeThreadPane: () => null }));
vi.mock('../workspace/WorkspaceProvider', () => ({ WorkspaceProvider: ({ children, threadActions }: { children: ReactNode; threadActions: ComponentProps<typeof WorkspaceProvider>['threadActions'] }) => <actionsContext.Provider value={threadActions ?? {}}>{children}</actionsContext.Provider> }));
vi.mock('../api/client', async importOriginal => ({ ...await importOriginal<typeof import('../api/client')>(), renameThread: vi.fn() }));
vi.mock('../shell/KodexShellView', () => ({ useNarrowThreadWorkspace: () => false, KodexShellView: () => {
  const actions = useContext(actionsContext); const catalog = useNativeCatalogSnapshot();
  return <><output aria-label="Saved chat title">{catalog?.chats[0]?.title}</output><button onClick={() => void actions.onRenameThread?.('chat', 'Native name')}>Submit rename</button></>;
} }));
it('routes rename through native RPC and waits for canonical catalog updates', async () => {
  let next: ((value: IteratorResult<CatalogSnapshot>) => void) | undefined;
  rpc.watchCatalog.mockResolvedValue({ [Symbol.asyncIterator]() { return { next: () => new Promise<IteratorResult<CatalogSnapshot>>(resolve => { next = resolve; }) }; } });
  rpc.renameChat.mockResolvedValue({ accepted: true });
  const client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  render(<QueryClientProvider client={client}><MantineProvider env="test"><NativeShell colorSchemeId="oled-black" appearance={DEFAULT_APPEARANCE_PREFERENCES} onAppearanceModeChange={vi.fn()} onThemeChange={vi.fn()} /></MantineProvider></QueryClientProvider>);
  await waitFor(() => expect(rpc.watchCatalog).toHaveBeenCalledOnce());
  const catalog: CatalogSnapshot = { epoch: 'epoch', revision: 1, projects: [], archivedChatIds: [], pinnedChatIds: [], chats: [{ id: 'chat', projectId: null, cwd: '/retained', title: 'Preview', name: null, pinned: false, notificationsEnabled: true }] };
  await act(async () => next?.({ value: catalog, done: false }));
  await userEvent.click(screen.getByRole('button', { name: 'Submit rename' }));
  await waitFor(() => expect(rpc.renameChat).toHaveBeenCalledWith({ chatId: 'chat', title: 'Native name' }));
  expect(screen.getByLabelText('Saved chat title')).toHaveTextContent('Preview');
  await act(async () => next?.({ value: { ...catalog, revision: 2, chats: [{ ...catalog.chats[0], name: 'Other client name', title: 'Other client name' }] }, done: false }));
  expect(screen.getByLabelText('Saved chat title')).toHaveTextContent('Other client name');
  expect(renameThread).not.toHaveBeenCalled(); expect(rpc.watchCatalog).toHaveBeenCalledOnce();
});
