import { act, cleanup, renderHook, waitFor } from '@testing-library/react';
import { afterEach, expect, it, vi } from 'vitest';
import { useNativeUnreadBadge } from './useNativeUnreadBadge';
const native = vi.hoisted(() => ({ read: vi.fn(), setBadge: vi.fn() }));
vi.mock('./nativePresenceBadgeClient', async original => ({ ...await original<typeof import('./nativePresenceBadgeClient')>(), createNativePresenceBadgeClient: () => ({ getUnreadBadge: native.read }) }));
vi.mock('../notifications/browserBadge', () => ({ setKodexAppBadge: native.setBadge }));
afterEach(() => { cleanup(); vi.resetAllMocks(); });
it('refreshes native authoritative badges from catalog, focus and foreground, preserving unknown/error state', async () => {
  native.read.mockResolvedValueOnce({ epoch: 'native', revision: 1, count: 7 });
  const view = renderHook(({ catalog }) => useNativeUnreadBadge(catalog), { initialProps: { catalog: { epoch: 'native', revision: 1 } } });
  await waitFor(() => expect(native.setBadge).toHaveBeenCalledWith(7));
  native.read.mockResolvedValueOnce({ epoch: 'native', revision: 2, count: null });
  view.rerender({ catalog: { epoch: 'native', revision: 1 } });
  await waitFor(() => expect(native.read).toHaveBeenCalledTimes(2));
  expect(native.setBadge).toHaveBeenCalledOnce();
  native.read.mockRejectedValueOnce(new Error('Inventory unavailable'));
  act(() => window.dispatchEvent(new Event('focus')));
  await waitFor(() => expect(native.read).toHaveBeenCalledTimes(3));
  expect(native.setBadge).toHaveBeenCalledOnce();
  native.read.mockResolvedValueOnce({ epoch: 'restarted', revision: 0, count: 0 });
  act(() => document.dispatchEvent(new Event('visibilitychange')));
  await waitFor(() => expect(native.setBadge).toHaveBeenLastCalledWith(0));
});
it('cancels overlap and rejects old reads and lower revisions, including after unknown inventory', async () => {
  let finish!: (value: unknown) => void; let oldSignal!: AbortSignal;
  native.read.mockImplementationOnce((_input, options) => { oldSignal = options.signal; return new Promise(resolve => { finish = resolve; }); });
  const view = renderHook(({ catalog }) => useNativeUnreadBadge(catalog), { initialProps: { catalog: { epoch: 'native', revision: 1 } } });
  await waitFor(() => expect(native.read).toHaveBeenCalledOnce());
  native.read.mockResolvedValueOnce({ epoch: 'native', revision: 5, count: 2 });
  view.rerender({ catalog: { epoch: 'native', revision: 1 } });
  await waitFor(() => expect(native.setBadge).toHaveBeenCalledWith(2));
  expect(oldSignal.aborted).toBe(true);
  await act(async () => finish({ epoch: 'native', revision: 10, count: 9 }));
  expect(native.setBadge).toHaveBeenCalledOnce();
  native.read.mockResolvedValueOnce({ epoch: 'native', revision: 6, count: null });
  act(() => window.dispatchEvent(new Event('online')));
  await waitFor(() => expect(native.read).toHaveBeenCalledTimes(3));
  native.read.mockResolvedValueOnce({ epoch: 'native', revision: 5, count: 1 });
  view.rerender({ catalog: { epoch: 'native', revision: 1 } });
  await waitFor(() => expect(native.read).toHaveBeenCalledTimes(4));
  expect(native.setBadge).toHaveBeenCalledOnce();
});
