export const queryKeys = {
  account: ["account"] as const,
  accountLoginCompletion: (loginId: string | null) => ["account-login-completion", loginId] as const,
  automationRunsRoot: ["automation-runs"] as const,
  automationRuns: (automationId: string) => ["automation-runs", automationId] as const,
  automations: ["automations"] as const,
  automationTombstones: ["automations", "tombstones"] as const,
  capabilities: ["capabilities"] as const,
  chatThreads: ["threads", "chat"] as const,
  composerSettingsRoot: ["composer-settings"] as const,
  composerSettings: (projectId: string | null, cwd?: string | null) => ["composer-settings", projectId ?? "global", cwd ?? null] as const,
  appSurface: (threadId: string) => ["threads", threadId, "app-surface"] as const,
  kodexControlPlugin: ["plugins", "kodex-control"] as const,
  models: ["models"] as const,
  mcpConfiguredServers: ["mcp", "configured-servers"] as const,
  mcpResource: (server: string, uri: string) => ["mcp", "servers", server, "resources", uri] as const,
  mcpServers: ["mcp", "servers"] as const,
  unreadBadge: ["unread-badge"] as const,
  notificationStatus: ["notifications", "status"] as const,
  permissionProfilesRoot: ["permission-profiles"] as const,
  permissionProfiles: (cwd: string | null) => ["permission-profiles", cwd ?? "global"] as const,
  pendingApprovals: ["approvals", "pending"] as const,
  sectionThreadsRoot: ["threads", "section"] as const,
  sectionThreads: (sectionId: string) => ["threads", "section", sectionId] as const,
  projectThreads: (projectId: string) => ["threads", "project", projectId] as const,
  projectThreadsRoot: ["threads", "project"] as const,
  projects: ["projects"] as const,
  threadPages: ["thread-pages"] as const,
  threadSettingsRoot: ["thread-settings"] as const,
  threadSettings: (threadId: string | null) => ["thread-settings", threadId] as const,
  queuedInputs: (threadId: string) => ["queued-inputs", threadId] as const,
  queuedInputsRoot: ["queued-inputs"] as const,
  rateLimits: ["account", "rate-limits"] as const,
  sidebarThreads: ["threads", "sidebar"] as const,
  skills: (cwd: string | null) => ["skills", cwd ?? "global"] as const,
  threadSubagentsRoot: ["thread-subagents"] as const,
  threadSubagents: (threadId: string | null) => ["thread-subagents", threadId] as const,
};
